In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

ModuleNotFoundError: No module named 'matplotlib'

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Matplotlib is building the font cache; this may take a moment.


In [2]:
print(x)

[['France' 40.0 49000.0]
 ['Germany' 36.0 62000.0]
 ['Spain' 30.0 58000.0]
 ['Germany' 46.0 nan]
 ['Spain' 35.0 78000.0]
 ['France' nan 48000.0]
 ['Germany' nan 67000.0]
 ['Spain' 50.0 83000.0]
 ['Spain' 37.0 61000.0]
 ['France' 44.0 44000.0]]


In [3]:
print(y)

['Yes' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes']


In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

ModuleNotFoundError: No module named 'sklearn'

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['France' 40.0 49000.0]
 ['Germany' 36.0 62000.0]
 ['Spain' 30.0 58000.0]
 ['Germany' 46.0 61000.0]
 ['Spain' 35.0 78000.0]
 ['France' 38.5 48000.0]
 ['Germany' 38.5 67000.0]
 ['Spain' 50.0 83000.0]
 ['Spain' 37.0 61000.0]
 ['France' 44.0 44000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 40.0 49000.0]
 [0.0 1.0 0.0 36.0 62000.0]
 [0.0 0.0 1.0 30.0 58000.0]
 [0.0 1.0 0.0 46.0 61000.0]
 [0.0 0.0 1.0 35.0 78000.0]
 [1.0 0.0 0.0 38.5 48000.0]
 [0.0 1.0 0.0 38.5 67000.0]
 [0.0 0.0 1.0 50.0 83000.0]
 [0.0 0.0 1.0 37.0 61000.0]
 [1.0 0.0 0.0 44.0 44000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[1 0 0 1 0 0 0 1 1 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 35.0 78000.0]
 [1.0 0.0 0.0 40.0 49000.0]
 [0.0 1.0 0.0 46.0 61000.0]
 [0.0 1.0 0.0 36.0 62000.0]
 [0.0 0.0 1.0 50.0 83000.0]
 [0.0 0.0 1.0 37.0 61000.0]
 [1.0 0.0 0.0 38.5 48000.0]]


In [13]:
print(x_test)

[[0.0 0.0 1.0 30.0 58000.0]
 [1.0 0.0 0.0 44.0 44000.0]
 [0.0 1.0 0.0 38.5 67000.0]]


In [14]:
print(y_train)

[0 1 1 0 1 1 0]


In [15]:
print(y_test)

[0 1 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_train[:, 3:])

ValueError: could not broadcast input array from shape (7,2) into shape (3,2)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 0.0 1.0 -1.0354928876609886 1.2102845667008924]
 [1.0 0.0 0.0 -0.06903285917739928 -1.1520978086864262]
 [0.0 1.0 0.0 1.090719175002908 -0.1745602740433979]
 [0.0 1.0 0.0 -0.8422008819642708 -0.09309881282314557]
 [0.0 0.0 1.0 1.8638871977897793 1.617591872802154]
 [0.0 0.0 1.0 -0.6489088762675529 -0.1745602740433979]
 [1.0 0.0 0.0 -0.35897086772247605 -1.2335592699066786]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 30.0 58000.00000000001]
 [1.0 0.0 0.0 44.0 44000.00000000001]
 [0.0 1.0 0.0 38.5 67000.00000000001]]
